version: "3.8"

services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  backend:
    build:
      context: ./
      dockerfile: .docker/backend/Dockerfile
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongo_db

volumes:
  db: